import { ComponentPropsWithRef } from '../../../../../../node_modules/react';
export interface FlxCardProps extends ComponentPropsWithRef<'div'> {
    cardStyle?: 'border' | 'raised';
}
declare const FlxCard: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<FlxCardProps, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>;
declare const MemoFlxCard: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<FlxCardProps, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>>;
declare const FlxCardHeader: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
    ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>;
declare const MemoFlxCardHeader: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
    ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>>;
declare const FlxCardTitle: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
    ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>;
declare const MemoFlxCardTitle: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
    ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>>;
declare const FlxCardSubtitle: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
    ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>;
declare const MemoFlxCardSubtitle: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
    ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>>;
declare const FlxCardContent: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
    ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>;
declare const MemoFlxCardContent: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
    ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
}, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>>;
declare const _default: {
    FlxCard: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<FlxCardProps, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>;
    FlxCardSubtitle: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
        ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>;
    FlxCardTitle: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
        ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>;
    FlxCardContent: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
        ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>;
    FlxCardHeader: import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
        ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>;
    MemoFlxCard: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<FlxCardProps, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>>;
    MemoFlxCardSubtitle: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
        ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>>;
    MemoFlxCardTitle: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
        ref?: ((instance: HTMLParagraphElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLParagraphElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLParagraphElement>>>;
    MemoFlxCardContent: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
        ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>>;
    MemoFlxCardHeader: import('../../../../../../node_modules/react').MemoExoticComponent<import('../../../../../../node_modules/react').ForwardRefExoticComponent<Omit<Omit<import('../../../../../../node_modules/react').DetailedHTMLProps<import('../../../../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
        ref?: ((instance: HTMLDivElement | null) => void | import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import('../../../../../../node_modules/react').DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import('../../../../../../node_modules/react').RefObject<HTMLDivElement> | null | undefined;
    }, "ref"> & import('../../../../../../node_modules/react').RefAttributes<HTMLDivElement>>>;
};
export default _default;
export { FlxCard, FlxCardSubtitle, FlxCardTitle, FlxCardContent, FlxCardHeader, MemoFlxCard, MemoFlxCardSubtitle, MemoFlxCardTitle, MemoFlxCardContent, MemoFlxCardHeader, };
